-- MySQL Script generated by MySQL Workbench
-- Fri Jun 26 23:35:34 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_107403046
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_107403046` ;

-- -----------------------------------------------------
-- Schema db_107403046
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_107403046` DEFAULT CHARACTER SET utf8 ;
USE `db_107403046` ;

-- -----------------------------------------------------
-- Table `db_107403046`.`tbl_User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_107403046`.`tbl_User` ;

CREATE TABLE IF NOT EXISTS `db_107403046`.`tbl_User` (
  `User_ID` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(100) NOT NULL,
  `lastname` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `salt` CHAR(64) NOT NULL,
  `Dob` DATE NOT NULL,
  `Register_Date Time` DATE NOT NULL,
  PRIMARY KEY (`User_ID`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `salt_UNIQUE` (`salt` ASC),
  UNIQUE INDEX `User_ID_UNIQUE` (`User_ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_107403046`.`tbl_Station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_107403046`.`tbl_Station` ;

CREATE TABLE IF NOT EXISTS `db_107403046`.`tbl_Station` (
  `Station_ID` INT NOT NULL AUTO_INCREMENT,
  `Station_Name` VARCHAR(100) NOT NULL,
  `Location_Marker` INT NOT NULL,
  `Time_Marker` INT NOT NULL,
  PRIMARY KEY (`Station_ID`),
  UNIQUE INDEX `Station_ID_UNIQUE` (`Station_ID` ASC),
  UNIQUE INDEX `Station_Name_UNIQUE` (`Station_Name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_107403046`.`tbl_Train`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_107403046`.`tbl_Train` ;

CREATE TABLE IF NOT EXISTS `db_107403046`.`tbl_Train` (
  `Train_ID` INT NOT NULL AUTO_INCREMENT,
  `Departure_Time` TIME NULL,
  `Departure_Station` INT NOT NULL,
  `Arrival_Time` TIME NULL,
  `Off_Date` DATE NULL,
  `On_Date` DATE NOT NULL,
  PRIMARY KEY (`Train_ID`, `Departure_Station`),
  INDEX `train_dep_station_fk_idx` (`Departure_Station` ASC),
  CONSTRAINT `train_dep_station_fk`
    FOREIGN KEY (`Departure_Station`)
    REFERENCES `db_107403046`.`tbl_Station` (`Station_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_107403046`.`tbl_UserCredential`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_107403046`.`tbl_UserCredential` ;

CREATE TABLE IF NOT EXISTS `db_107403046`.`tbl_UserCredential` (
  `UserCredential` INT NOT NULL AUTO_INCREMENT,
  `User_ID` INT NOT NULL,
  `HashedPwd` VARCHAR(255) NOT NULL,
  `Create_DateTime` DATETIME NOT NULL,
  PRIMARY KEY (`UserCredential`, `User_ID`),
  INDEX `userCredential_user_id_fk_idx` (`User_ID` ASC),
  UNIQUE INDEX `UserCredential_UNIQUE` (`UserCredential` ASC),
  UNIQUE INDEX `User_ID_UNIQUE` (`User_ID` ASC),
  CONSTRAINT `userCredential_user_id_fk`
    FOREIGN KEY (`User_ID`)
    REFERENCES `db_107403046`.`tbl_User` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_107403046`.`tbl_Seat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_107403046`.`tbl_Seat` ;

CREATE TABLE IF NOT EXISTS `db_107403046`.`tbl_Seat` (
  `Seat_ID` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`Seat_ID`),
  UNIQUE INDEX `Seat_ID_UNIQUE` (`Seat_ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_107403046`.`tbl_Ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_107403046`.`tbl_Ticket` ;

CREATE TABLE IF NOT EXISTS `db_107403046`.`tbl_Ticket` (
  `Ticket_ID` INT NOT NULL AUTO_INCREMENT,
  `User_ID` INT NOT NULL,
  `Train_Date` DATE NOT NULL,
  `Train_ID` INT NOT NULL,
  `Departure_Station` INT NOT NULL,
  `Arrival_Station` INT NOT NULL,
  `Seat_ID` VARCHAR(64) NOT NULL,
  `Price` INT NOT NULL,
  `Book_Time` DATETIME NOT NULL,
  `Pay_Time` DATETIME NULL,
  PRIMARY KEY (`Ticket_ID`, `Seat_ID`, `Train_ID`, `User_ID`),
  INDEX `ticket_user_id_fk_idx` (`User_ID` ASC),
  INDEX `ticket_train_id_fk_idx` (`Train_ID` ASC),
  INDEX `ticket_arr_station_fk_idx` (`Arrival_Station` ASC),
  UNIQUE INDEX `Ticket_ID_UNIQUE` (`Ticket_ID` ASC),
  CONSTRAINT `ticket_user_id_fk`
    FOREIGN KEY (`User_ID`)
    REFERENCES `db_107403046`.`tbl_User` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ticket_train_id_fk`
    FOREIGN KEY (`Train_ID`)
    REFERENCES `db_107403046`.`tbl_Train` (`Train_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ticket_seat_id_fk`
    FOREIGN KEY (`Seat_ID`)
    REFERENCES `db_107403046`.`tbl_Seat` (`Seat_ID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `ticket_arr_station_fk`
    FOREIGN KEY (`Arrival_Station`)
    REFERENCES `db_107403046`.`tbl_Station` (`Station_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
